apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wagtail-website-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx # Ensure you have an NGINX Ingress Controller installed or change this to your Ingress class
  rules:
  - host: wagtail.mydomain.it
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wagtail-website-service
            port:
              number: 80