apiVersion: v1
kind: Secret
metadata:
  name: wagtail-website-secret
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ base64_encoded_key }}
  DJANGO_SUPERUSER_USERNAME: {{ base64_encoded_username }}
  DJANGO_SUPERUSER_EMAIL: {{ base64_encoded_email }}
  DJANGO_SUPERUSER_PASSWORD: {{ base64_encoded_password }}
